console.log(4+4);    //ADDING
console.log(10-2);   //SUBTRACK
console.log(8*1);    //MULTIPLY
console.log(64/8);   //DIVIDE
// IF YOU WILL CHANGE VALUES/NUMBERS,SO ANSWER WILL BE CHANGE,ITS SIMPLE FOR MATHIMATICLE PROBLUMS SOLVING.